package metric

const (
	// Liquidation event
	LIQUIDATION_RUN_JOB                = "LIQUIDATION_RUN_JOB"
	LIQUIDATION_RUN_JOB_2              = "LIQUIDATION_RUN_JOB_2"
	LIQUIDATION_RUN_JOB_3              = "LIQUIDATION_RUN_JOB_3"
	LIQUIDATION_RUN_JOB_4              = "LIQUIDATION_RUN_JOB_4"
	LIQUIDATION_RUN_JOB_5              = "LIQUIDATION_RUN_JOB_5"
	LIQUIDATION_GET_ALL_SUBACCOUNT_IDS = "LIQUIDATION_GET_ALL_SUBACCOUNT_IDS"
	LIQUIDATION_WRITE_REDIS_STATE      = "LIQUIDATION_WRITE_REDIS_STATE"
	LIQUIDATION_FETCH_REDIS_STATE      = "LIQUIDATION_FETCH_REDIS_STATE"

	// Funds Monitoring
	FUNDS_MONITORING_RUN_JOB = "FUNDS_MONITORING_RUN_JOB"

	// Kroma Burn
	KROMA_BURN_RUN_JOB          = "KROMA_BURN_RUN_JOB"

	// App state
	GET_APP_STATE         = "GET_APP_STATE"
	GET_ALL_ORACLE_PRICES = "GET_ALL_ORACLE_PRICES"

	// User state
	GET_SUBACCOUNTS_BALANCES      = "GET_SUBACCOUNTS_BALANCES"
	GET_SUBACCOUNTS_BALANCES_FAST = "GET_SUBACCOUNTS_BALANCES_FAST"

	// Cron server
	SEQUENCER_BATCHING = "SEQUENCER_BATCHING"
	PRUNE_ORDERS       = "PRUNE_ORDERS"

	// Transaction events
	WRITE_BALANCES_FOR_TXN  = "WRITE_BALANCES_FOR_TXN"
	READ_BALANCES_FOR_TXN   = "READ_BALANCES_FOR_TXN"
	DELETE_BALANCES_FOR_TXN = "DELETE_BALANCES_FOR_TXN"

	// AP server events
	CLAIM_LOGX_TXN = "CLAIM_LOGX_TXN"

	CLAIM_CAMPAIGN_REWARDS = "CLAIM_CAMPAIGN_REWARDS"
	DOWNLOAD_TRADE_HISTORY = "DOWNLOAD_TRADE_HISTORY"
)
