//! Golden-vector parity (gate G1): Rust must reproduce vectors/*.json generated by Go.
use near_sdk::borsh;
use near_stocks_core::{eip712, identity};
use serde_json::Value;

fn load(name: &str) -> Value {
    let path = format!("{}/../../vectors/{}", env!("CARGO_MANIFEST_DIR"), name);
    serde_json::from_str(&std::fs::read_to_string(&path).expect(&path)).unwrap()
}

fn unhex(s: &str) -> Vec<u8> {
    hex::decode(s.trim_start_matches("0x")).unwrap()
}

fn arr<const N: usize>(s: &str) -> [u8; N] {
    unhex(s).try_into().unwrap()
}

fn hx(b: &[u8]) -> String {
    format!("0x{}", hex::encode(b))
}

#[test]
fn addr20_and_subaccount() {
    let v = load("addr20.json");
    for c in v["valid"].as_array().unwrap() {
        let acct = c["accountId"].as_str().unwrap();
        let want = c["addr20"].as_str().unwrap().to_lowercase();
        assert_eq!(hx(&identity::addr20(acct)), want, "addr20 {acct}");
        let sub = identity::subaccount_id(c["brokerId"].as_u64().unwrap(), acct, c["subaccountNumber"].as_u64().unwrap());
        assert_eq!(hx(&sub), c["subaccountBytes32"].as_str().unwrap(), "sub32 {acct}");
    }
}

fn order_from(msg: &Value) -> eip712::Order {
    eip712::Order {
        subaccount: arr(msg["subAccountId"].as_str().unwrap()),
        price_x18: msg["priceX18"].as_str().unwrap().parse().unwrap(),
        amount: msg["amount"].as_str().unwrap().parse().unwrap(),
        expiration: msg["expiration"].as_str().unwrap().parse().unwrap(),
        is_reduce: msg["isReduce"].as_str().unwrap() == "true",
        session_key: arr(msg["sessionKey"].as_str().unwrap()),
        product_id: msg["productId"].as_str().unwrap().parse().unwrap(),
    }
}

#[test]
fn eip712_order_digest_and_recovery() {
    let v = load("eip712.json");
    for c in v["order"].as_array().unwrap() {
        let d = &c["domain"];
        assert_eq!(d["name"], eip712::DOMAIN_NAME);
        assert_eq!(d["version"], eip712::DOMAIN_VERSION);
        let chain_id = d["chainId"].as_u64().unwrap();
        let vc = eip712::verifying_contract(d["contractAccount"].as_str().unwrap());
        assert_eq!(hx(&vc), d["verifyingContract"].as_str().unwrap().to_lowercase());

        let sep = eip712::domain_separator(chain_id, &vc);
        assert_eq!(hx(&sep), d["domainSeparator"].as_str().unwrap());
        assert_eq!(hx(&eip712::order_type_hash()), c["typeHash"].as_str().unwrap());

        let order = order_from(&c["message"]);
        let sh = eip712::order_struct_hash(&order, chain_id);
        assert_eq!(hx(&sh), c["structHash"].as_str().unwrap());
        let digest = eip712::typed_digest(&sep, &sh);
        assert_eq!(hx(&digest), c["digest"].as_str().unwrap());

        let sig = unhex(c["signature"].as_str().unwrap());
        let signer = eip712::recover_signer(&digest, &sig).expect("recover");
        assert_eq!(hx(&signer), c["signer"].as_str().unwrap().to_lowercase());

        // v in 0/1 form recovers the same address
        let mut sig01 = sig.clone();
        sig01[64] -= 27;
        assert_eq!(eip712::recover_signer(&digest, &sig01), Some(signer));

        // wrong chain id must not recover the signer
        let other = eip712::typed_digest(&sep, &eip712::order_struct_hash(&order, chain_id + 1));
        assert_ne!(eip712::recover_signer(&other, &sig), Some(signer));

        // bad v / length rejected
        let mut bad = sig.clone();
        bad[64] = 5;
        assert_eq!(eip712::recover_signer(&digest, &bad), None);
        assert_eq!(eip712::recover_signer(&digest, &sig[..64]), None);
    }
}

#[test]
fn borsh_order_payload() {
    let v = load("borsh.json");
    let b = &v["order"];
    let order = eip712::Order {
        subaccount: arr(b["subaccount"].as_str().unwrap()),
        price_x18: b["priceX18"].as_str().unwrap().parse().unwrap(),
        amount: b["amount"].as_str().unwrap().parse().unwrap(),
        expiration: b["expiration"].as_str().unwrap().parse().unwrap(),
        is_reduce: b["isReduce"].as_bool().unwrap(),
        session_key: arr(b["sessionKey"].as_str().unwrap()),
        product_id: b["productId"].as_u64().unwrap() as u32,
    };
    let enc = borsh::to_vec(&order).unwrap();
    assert_eq!(hx(&enc), b["borshHex"].as_str().unwrap());
    let mut envelope = vec![b["typeByte"].as_u64().unwrap() as u8];
    envelope.extend_from_slice(&enc);
    assert_eq!(hx(&envelope), b["envelopeHex"].as_str().unwrap());
    let back: eip712::Order = borsh::from_slice(&enc).unwrap();
    assert_eq!(back, order);
}

#[test]
fn near_withdraw_digest_matches_go_and_ts() {
    let v = load("nearsign.json");
    let w = &v["withdraw"];
    let chain_id = v["chainId"].as_u64().unwrap();
    let vc = eip712::verifying_contract(v["contractAccount"].as_str().unwrap());
    let req = eip712::NearWithdraw {
        subaccount: arr(w["subAccountId"].as_str().unwrap()),
        session_key: arr(w["sessionKey"].as_str().unwrap()),
        product_id: w["productId"].as_u64().unwrap() as u32,
        amount: w["amount"].as_str().unwrap().parse().unwrap(),
        nonce: w["nonce"].as_str().unwrap().parse().unwrap(),
        receiver: w["receiver"].as_str().unwrap().to_string(),
    };
    let digest = eip712::typed_digest(&eip712::domain_separator(chain_id, &vc), &eip712::near_withdraw_struct_hash(&req, chain_id));
    assert_eq!(hx(&digest), w["digest"].as_str().unwrap());
    let signer = eip712::recover_signer(&digest, &unhex(w["signature"].as_str().unwrap())).unwrap();
    assert_eq!(hx(&signer), w["sessionKey"].as_str().unwrap().to_lowercase());
    // any change to the receiver changes the digest
    let mut other = req.clone();
    other.receiver = "mallory.near".into();
    assert_ne!(eip712::near_withdraw_struct_hash(&other, chain_id), eip712::near_withdraw_struct_hash(&req, chain_id));
}
