package types

const (
	PERPTICK_TXN                 = 0
	LIQUIDATE_SUBACCOUNT_TXN     = 1
	FINALISE_DEPOSIT_TXN         = 2
	WITHDRAW_COLLATERAL_TXN      = 3
	DUMMY_PLACEHOLDER_TXN        = 4
	MATCH_ORDERS_TXN             = 5
	DUMMY_PLACEHOLDER_1_TXN      = 6
	MANUAL_ASSERT_TXN            = 7
	UPDATE_PRODUCT_TXN           = 8
	UPDATE_FEE_RATES_TXN         = 9
	SHIFT_BALANCE_TXN            = 10
	SHIFT_BALANCE_KROMA_TXN      = 11
	BURN_BALANCE_KROMA_TXN       = 12
	WITHDRAW_LOGX_TXN            = 13
	CLAIM_REWARDS_TXN            = 14
	STAKE_LOGX_TXN               = 15
	UNSTAKE_LOGX_TXN             = 16
	REGISTER_TXN                 = 17
	CLAIM_LOGX_TXN               = 18
	SETTLE_USER_PNL_TXN          = 19
	SOCIALISE_SUBACCOUNT_TXN     = 20
	SET_NONCE_TXN                = 21
	REWARD_RATE_TICK_TXN         = 22
	CLAIM_CAMPAIGN_REWARDS_TXN   = 23
	PLACE_OPTIONS_BET_TXN        = 24
	CLOSE_OPTIONS_BET_TXN        = 25
	PRE_MARKET_ORDER_REQUEST_TXN = 26
	SYN_SPOT_ORDER_REQUEST_TXN   = 27
)
